apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "onekg.fullname" . }}-config
  labels:
    app.kubernetes.io/name: {{ include "onekg.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  {{- range $section, $values := .Values.midil.config }}
  {{- range $key, $value := $values }}
  {{- if kindIs "map" $value }}
  MIDIL__{{ $section | upper }}__{{ $key | upper }}: {{ $value | toJson | quote }}
  {{- else }}
  MIDIL__{{ $section | upper }}__{{ $key | upper }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
  {{- end }}

  {{- with .Values.config.extraConfig }}
  {{- range $key, $value := . }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
