apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "onekg.fullname" . }}-config
  labels:
    app.kubernetes.io/name: {{ include "onekg.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
{{- range $section, $values := .Values.midil.config }}
{{ include "onekg.flatten" (dict "root" "MIDIL" "section" ($section | upper) "values" $values) | indent 2 }}
{{- end }}

{{- with .Values.config.extraConfig }}
{{- range $key, $value := . }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- end }}
