{{- if .Values.image.createPullSecret }}
{{- $username := default "" .Values.image.credentials.username -}}
{{- $password := default "" .Values.image.credentials.password -}}
{{- $email := default "" .Values.image.credentials.email -}}
{{- $server := default "ghcr.io" .Values.image.dockerServer -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.image.pullSecretName | default "ghcr-secret" }}
  labels:
    {{- include "onekg.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ dict "auths" (dict $server (dict "username" $username "password" $password "email" $email "auth" (printf "%s:%s" $username $password | b64enc))) | toJson | b64enc | quote }}
{{- end }}

