{{- if .Values.ingressRoute.enabled }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "onekg.fullname" . }}-strip-prefix
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "onekg.labels" . | nindent 4 }}
spec:
  stripPrefix:
    prefixes:
      - {{ .Values.ingressRoute.basePath }}
    forceSlash: true
{{- end }}

---
{{- if .Values.cors.enabled }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "onekg.fullname" . }}-cors
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "onekg.labels" . | nindent 4 }}
spec:
  headers:
    accessControlAllowMethods:
      {{- if .Values.cors.allowedMethods }}
      {{- range .Values.cors.allowedMethods }}
      - {{ . | quote }}
      {{- end }}
      {{- else }}
      - "GET"
      - "POST"
      - "PUT"
      - "DELETE"
      - "OPTIONS"
      {{- end }}

    accessControlAllowOriginList:
      {{- $env := .Values.cors.environment | default "production" }}
      {{- $allowed := .Values.cors.allowedOrigins }}
      {{- if $allowed }}
      {{- if kindIs "map" $allowed }}
      {{- $origins := index $allowed $env }}
      {{- if $origins }}
      {{- range $origins }}
      - {{ . | quote }}
      {{- end }}
      {{- else }}
      - "https://{{ .Values.ingressRoute.host }}"
      {{- end }}
      {{- else if kindIs "array" $allowed }}
      {{- range $allowed }}
      - {{ . | quote }}
      {{- end }}
      {{- else }}
      - "https://{{ .Values.ingressRoute.host }}"
      {{- end }}
      {{- else }}
      - "https://{{ .Values.ingressRoute.host }}"
      {{- end }}

    accessControlAllowHeaders:
      {{- if .Values.cors.allowedHeaders }}
      {{- range .Values.cors.allowedHeaders }}
      - {{ . | quote }}
      {{- end }}
      {{- else }}
      - "Content-Type"
      - "Authorization"
      - "X-Requested-With"
      - "Accept"
      - "Cache-Control"
      {{- end }}

    accessControlAllowCredentials: {{ .Values.cors.allowCredentials | default true }}
    accessControlMaxAge: {{ .Values.cors.maxAge | default 86400 }}
{{- end }}
