apiVersion: v1
kind: Secret
metadata:
  name: {{ include "onekg.fullname" . }}-secrets
  labels:
    app.kubernetes.io/name: {{ include "onekg.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  {{- range $section, $values := .Values.midil.secrets }}
  {{- range $key, $value := $values }}
  {{- if kindIs "map" $value }}
  MIDIL__{{ $section | upper }}__{{ $key | upper }}: {{ $value | toJson | b64enc | quote }}
  {{- else }}
  MIDIL__{{ $section | upper }}__{{ $key | upper }}: {{ $value | b64enc | quote }}
  {{- end }}
  {{- end }}
  {{- end }}

  {{- with .Values.secrets.extraSecrets }}
  {{- range $key, $value := . }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
  {{- end }}
