apiVersion: v1
kind: Service
metadata:
  name: {{ include "onekg.fullname" . }}
  labels:
    {{- include "onekg.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.http.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.monitoring.enabled }}
    - port: {{ .Values.monitoring.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    {{- include "onekg.selectorLabels" . | nindent 4 }}
